name: test.yml
on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go 1.21.x
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.23.x'
      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Test with Go
        run: go test -json > TestResults.json

      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-test-results
          path: TestResults.json
          retention-days: 90

      - name: Fuzz Test with Go
        run: go test -fuzz=Fuzz -fuzztime 60s -json > FuzzResults.json

      - name: Upload Go Fuzz test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-fuzz-results
          path: FuzzResults.json
          retention-days: 90
